export type PasswordResetEmail = {
  /** The absolute action link generated by adminClient.auth.admin.generateLink. */
  link: string
}

export function renderPasswordResetEmail({ link }: PasswordResetEmail): { subject: string; html: string } {
  const subject = 'Reset your First Equity Funding Portal password'
  const html = `
    <p style="font-family: Arial, sans-serif; font-size: 14px; color: #333;">Hi,</p>
    <p style="font-family: Arial, sans-serif; font-size: 14px; color: #333;">
      We received a request to reset the password for your <strong>First Equity Funding Online Portal</strong> account.
      Click the button below to set a new password.
    </p>
    <p style="margin-top: 24px;">
      <a href="${link}" style="background-color: #1F5D8F; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-family: Arial, sans-serif; font-size: 14px; font-weight: bold;">
        Reset Password
      </a>
    </p>
    <p style="font-family: Arial, sans-serif; font-size: 12px; color: #999; margin-top: 24px;">
      This link expires in 24 hours. If you didn't request a password reset, you can safely ignore this email.
    </p>
    <p style="font-family: Arial, sans-serif; font-size: 12px; color: #999;">First Equity Funding Online Portal</p>
  `
  return { subject, html }
}